### ISSUE TITLE
Initialise plugin

### ISSUE THREAD

**Issue by mk4111** [postgres-plugin/insights#1]
Quick todo list

- [x] add package.json
- [x] start README.md
- [x] Lint, Coverage and Testing
- [x] config
- [x] example server
- [x] register plugins
- [x] add mock data to ce100-mock-data plugin
- [x] make routes for browse ( #2), add ( #4 ), edit ( #7 ), getById ( #6 ), toggle ( #8 ) 
- [x] test endpoints and queries

**Comment by SimonLab** [comment]
Thanks @mk4111 resolved with #3
